var annotated_dup =
[
    [ "CryptoTA", "namespace_crypto_t_a.html", [
      [ "Apis", "namespace_crypto_t_a_1_1_apis.html", [
        [ "Balance", "class_crypto_t_a_1_1_apis_1_1_balance.html", "class_crypto_t_a_1_1_apis_1_1_balance" ],
        [ "Fees", "class_crypto_t_a_1_1_apis_1_1_fees.html", "class_crypto_t_a_1_1_apis_1_1_fees" ],
        [ "Order", "class_crypto_t_a_1_1_apis_1_1_order.html", "class_crypto_t_a_1_1_apis_1_1_order" ],
        [ "OrderBook", "class_crypto_t_a_1_1_apis_1_1_order_book.html", null ],
        [ "OrderBookEntry", "class_crypto_t_a_1_1_apis_1_1_order_book_entry.html", "class_crypto_t_a_1_1_apis_1_1_order_book_entry" ],
        [ "TickData", "class_crypto_t_a_1_1_apis_1_1_tick_data.html", null ],
        [ "TradingBalance", "class_crypto_t_a_1_1_apis_1_1_trading_balance.html", "class_crypto_t_a_1_1_apis_1_1_trading_balance" ],
        [ "TradingPair", "class_crypto_t_a_1_1_apis_1_1_trading_pair.html", "class_crypto_t_a_1_1_apis_1_1_trading_pair" ],
        [ "WebsocketsToken", "class_crypto_t_a_1_1_apis_1_1_websockets_token.html", null ]
      ] ],
      [ "UserControls", "namespace_crypto_t_a_1_1_user_controls.html", [
        [ "PointShapeLineChart", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart.html", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart" ],
        [ "PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control" ]
      ] ],
      [ "AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", "class_crypto_t_a_1_1_accounts_window" ],
      [ "App", "class_crypto_t_a_1_1_app.html", "class_crypto_t_a_1_1_app" ],
      [ "DataDownload", "class_crypto_t_a_1_1_data_download.html", "class_crypto_t_a_1_1_data_download" ],
      [ "DownloadWindow", "class_crypto_t_a_1_1_download_window.html", "class_crypto_t_a_1_1_download_window" ],
      [ "MainWindow", "class_crypto_t_a_1_1_main_window.html", "class_crypto_t_a_1_1_main_window" ],
      [ "UserControl1", "class_crypto_t_a_1_1_user_control1.html", "class_crypto_t_a_1_1_user_control1" ]
    ] ],
    [ "Kraken", "namespace_kraken.html", [
      [ "Add", "class_kraken_1_1_add.html", "class_kraken_1_1_add" ],
      [ "Add2", "class_kraken_1_1_add2.html", null ],
      [ "Address", "class_kraken_1_1_address.html", "class_kraken_1_1_address" ],
      [ "Addresses", "class_kraken_1_1_addresses.html", "class_kraken_1_1_addresses" ],
      [ "Addresses2", "class_kraken_1_1_addresses2.html", null ],
      [ "Anonymous", "class_kraken_1_1_anonymous.html", "class_kraken_1_1_anonymous" ],
      [ "ApiException", "class_kraken_1_1_api_exception.html", null ],
      [ "Asset", "class_kraken_1_1_asset.html", "class_kraken_1_1_asset" ],
      [ "Balance", "class_kraken_1_1_balance.html", null ],
      [ "Balance2", "class_kraken_1_1_balance2.html", null ],
      [ "Balance3", "class_kraken_1_1_balance3.html", "class_kraken_1_1_balance3" ],
      [ "Balance4", "class_kraken_1_1_balance4.html", null ],
      [ "Batchadd", "class_kraken_1_1_batchadd.html", "class_kraken_1_1_batchadd" ],
      [ "Batchadd2", "class_kraken_1_1_batchadd2.html", null ],
      [ "Batchcancel", "class_kraken_1_1_batchcancel.html", null ],
      [ "Batchcancel2", "class_kraken_1_1_batchcancel2.html", null ],
      [ "Cancel", "class_kraken_1_1_cancel.html", "class_kraken_1_1_cancel" ],
      [ "Cancel2", "class_kraken_1_1_cancel2.html", null ],
      [ "Cancel3", "class_kraken_1_1_cancel3.html", "class_kraken_1_1_cancel3" ],
      [ "Closed", "class_kraken_1_1_closed.html", "class_kraken_1_1_closed" ],
      [ "Closed2", "class_kraken_1_1_closed2.html", "class_kraken_1_1_closed2" ],
      [ "Deposit", "class_kraken_1_1_deposit.html", "class_kraken_1_1_deposit" ],
      [ "Depth", "class_kraken_1_1_depth.html", null ],
      [ "Descr", "class_kraken_1_1_descr.html", "class_kraken_1_1_descr" ],
      [ "Descr2", "class_kraken_1_1_descr2.html", "class_kraken_1_1_descr2" ],
      [ "Descr3", "class_kraken_1_1_descr3.html", "class_kraken_1_1_descr3" ],
      [ "Edit", "class_kraken_1_1_edit.html", "class_kraken_1_1_edit" ],
      [ "Edit2", "class_kraken_1_1_edit2.html", null ],
      [ "Error", "class_kraken_1_1_error.html", null ],
      [ "Fees", "class_kraken_1_1_fees.html", "class_kraken_1_1_fees" ],
      [ "History", "class_kraken_1_1_history.html", "class_kraken_1_1_history" ],
      [ "History2", "class_kraken_1_1_history2.html", null ],
      [ "Info", "class_kraken_1_1_info.html", "class_kraken_1_1_info" ],
      [ "Info2", "class_kraken_1_1_info2.html", null ],
      [ "Info3", "class_kraken_1_1_info3.html", "class_kraken_1_1_info3" ],
      [ "Info4", "class_kraken_1_1_info4.html", "class_kraken_1_1_info4" ],
      [ "Info5", "class_kraken_1_1_info5.html", "class_kraken_1_1_info5" ],
      [ "KrakenClient", "class_kraken_1_1_kraken_client.html", "class_kraken_1_1_kraken_client" ],
      [ "Ledger", "class_kraken_1_1_ledger.html", "class_kraken_1_1_ledger" ],
      [ "Lock", "class_kraken_1_1_lock.html", "class_kraken_1_1_lock" ],
      [ "Lock2", "class_kraken_1_1_lock2.html", null ],
      [ "Method", "class_kraken_1_1_method.html", "class_kraken_1_1_method" ],
      [ "Methods", "class_kraken_1_1_methods.html", "class_kraken_1_1_methods" ],
      [ "Methods2", "class_kraken_1_1_methods2.html", null ],
      [ "Minimum_amount", "class_kraken_1_1_minimum__amount.html", null ],
      [ "Ohlc", "class_kraken_1_1_ohlc.html", null ],
      [ "Open2", "class_kraken_1_1_open2.html", "class_kraken_1_1_open2" ],
      [ "Order", "class_kraken_1_1_order.html", "class_kraken_1_1_order" ],
      [ "OrderBookEntry", "class_kraken_1_1_order_book_entry.html", "class_kraken_1_1_order_book_entry" ],
      [ "Orders", "class_kraken_1_1_orders.html", "class_kraken_1_1_orders" ],
      [ "Orders2", "class_kraken_1_1_orders2.html", "class_kraken_1_1_orders2" ],
      [ "Orders3", "class_kraken_1_1_orders3.html", "class_kraken_1_1_orders3" ],
      [ "Pairs", "class_kraken_1_1_pairs.html", "class_kraken_1_1_pairs" ],
      [ "Query", "class_kraken_1_1_query.html", "class_kraken_1_1_query" ],
      [ "Query2", "class_kraken_1_1_query2.html", null ],
      [ "Query3", "class_kraken_1_1_query3.html", null ],
      [ "Recent", "class_kraken_1_1_recent.html", "class_kraken_1_1_recent" ],
      [ "Recent2", "class_kraken_1_1_recent2.html", null ],
      [ "Recent3", "class_kraken_1_1_recent3.html", "class_kraken_1_1_recent3" ],
      [ "Recent4", "class_kraken_1_1_recent4.html", null ],
      [ "Response", "class_kraken_1_1_response.html", null ],
      [ "Response10", "class_kraken_1_1_response10.html", null ],
      [ "Response11", "class_kraken_1_1_response11.html", null ],
      [ "Response12", "class_kraken_1_1_response12.html", "class_kraken_1_1_response12" ],
      [ "Response13", "class_kraken_1_1_response13.html", null ],
      [ "Response14", "class_kraken_1_1_response14.html", null ],
      [ "Response15", "class_kraken_1_1_response15.html", null ],
      [ "Response16", "class_kraken_1_1_response16.html", null ],
      [ "Response17", "class_kraken_1_1_response17.html", null ],
      [ "Response18", "class_kraken_1_1_response18.html", null ],
      [ "Response2", "class_kraken_1_1_response2.html", "class_kraken_1_1_response2" ],
      [ "Response3", "class_kraken_1_1_response3.html", null ],
      [ "Response4", "class_kraken_1_1_response4.html", "class_kraken_1_1_response4" ],
      [ "Response5", "class_kraken_1_1_response5.html", null ],
      [ "Response6", "class_kraken_1_1_response6.html", null ],
      [ "Response7", "class_kraken_1_1_response7.html", null ],
      [ "Response8", "class_kraken_1_1_response8.html", "class_kraken_1_1_response8" ],
      [ "Response9", "class_kraken_1_1_response9.html", null ],
      [ "Result", "class_kraken_1_1_result.html", "class_kraken_1_1_result" ],
      [ "Result10", "class_kraken_1_1_result10.html", null ],
      [ "Result11", "class_kraken_1_1_result11.html", "class_kraken_1_1_result11" ],
      [ "Result12", "class_kraken_1_1_result12.html", "class_kraken_1_1_result12" ],
      [ "Result13", "class_kraken_1_1_result13.html", "class_kraken_1_1_result13" ],
      [ "Result14", "class_kraken_1_1_result14.html", "class_kraken_1_1_result14" ],
      [ "Result15", "class_kraken_1_1_result15.html", "class_kraken_1_1_result15" ],
      [ "Result16", "class_kraken_1_1_result16.html", "class_kraken_1_1_result16" ],
      [ "Result17", "class_kraken_1_1_result17.html", "class_kraken_1_1_result17" ],
      [ "Result18", "class_kraken_1_1_result18.html", "class_kraken_1_1_result18" ],
      [ "Result19", "class_kraken_1_1_result19.html", "class_kraken_1_1_result19" ],
      [ "Result2", "class_kraken_1_1_result2.html", "class_kraken_1_1_result2" ],
      [ "Result20", "class_kraken_1_1_result20.html", "class_kraken_1_1_result20" ],
      [ "Result21", "class_kraken_1_1_result21.html", "class_kraken_1_1_result21" ],
      [ "Result22", "class_kraken_1_1_result22.html", "class_kraken_1_1_result22" ],
      [ "Result23", "class_kraken_1_1_result23.html", "class_kraken_1_1_result23" ],
      [ "Result24", "class_kraken_1_1_result24.html", "class_kraken_1_1_result24" ],
      [ "Result25", "class_kraken_1_1_result25.html", "class_kraken_1_1_result25" ],
      [ "Result3", "class_kraken_1_1_result3.html", "class_kraken_1_1_result3" ],
      [ "Result4", "class_kraken_1_1_result4.html", "class_kraken_1_1_result4" ],
      [ "Result5", "class_kraken_1_1_result5.html", null ],
      [ "Result6", "class_kraken_1_1_result6.html", "class_kraken_1_1_result6" ],
      [ "Result7", "class_kraken_1_1_result7.html", "class_kraken_1_1_result7" ],
      [ "Result8", "class_kraken_1_1_result8.html", "class_kraken_1_1_result8" ],
      [ "Result9", "class_kraken_1_1_result9.html", "class_kraken_1_1_result9" ],
      [ "Rewards", "class_kraken_1_1_rewards.html", "class_kraken_1_1_rewards" ],
      [ "Spread", "class_kraken_1_1_spread.html", null ],
      [ "Spread2", "class_kraken_1_1_spread2.html", null ],
      [ "TickData", "class_kraken_1_1_tick_data.html", null ],
      [ "Ticker", "class_kraken_1_1_ticker.html", "class_kraken_1_1_ticker" ],
      [ "Ticker2", "class_kraken_1_1_ticker2.html", null ],
      [ "Time", "class_kraken_1_1_time.html", null ],
      [ "Trade", "class_kraken_1_1_trade.html", null ],
      [ "Trade2", "class_kraken_1_1_trade2.html", "class_kraken_1_1_trade2" ],
      [ "Trades", "class_kraken_1_1_trades.html", null ],
      [ "Transaction", "class_kraken_1_1_transaction.html", "class_kraken_1_1_transaction" ],
      [ "Volume", "class_kraken_1_1_volume.html", "class_kraken_1_1_volume" ],
      [ "Withdrawal", "class_kraken_1_1_withdrawal.html", "class_kraken_1_1_withdrawal" ],
      [ "Withdrawal2", "class_kraken_1_1_withdrawal2.html", null ],
      [ "Withdrawal3", "class_kraken_1_1_withdrawal3.html", "class_kraken_1_1_withdrawal3" ]
    ] ],
    [ "REghZy", "namespace_r_egh_zy.html", [
      [ "Themes", "namespace_r_egh_zy_1_1_themes.html", [
        [ "Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", "class_r_egh_zy_1_1_themes_1_1_controls" ]
      ] ]
    ] ],
    [ "XamlGeneratedNamespace", "namespace_xaml_generated_namespace.html", [
      [ "GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", "class_xaml_generated_namespace_1_1_generated_internal_type_helper" ]
    ] ]
];