var hierarchy =
[
    [ "Kraken.Add", "class_kraken_1_1_add.html", null ],
    [ "Kraken.Add2", "class_kraken_1_1_add2.html", null ],
    [ "Kraken.Address", "class_kraken_1_1_address.html", null ],
    [ "Kraken.Addresses", "class_kraken_1_1_addresses.html", null ],
    [ "Kraken.Addresses2", "class_kraken_1_1_addresses2.html", null ],
    [ "Kraken.Anonymous", "class_kraken_1_1_anonymous.html", null ],
    [ "ApiException", null, [
      [ "Kraken.ApiException< TResult >", "class_kraken_1_1_api_exception.html", null ]
    ] ],
    [ "Application", null, [
      [ "CryptoTA.App", "class_crypto_t_a_1_1_app.html", null ]
    ] ],
    [ "System.Windows.Application", null, [
      [ "CryptoTA.App", "class_crypto_t_a_1_1_app.html", null ],
      [ "CryptoTA.App", "class_crypto_t_a_1_1_app.html", null ]
    ] ],
    [ "Kraken.Asset", "class_kraken_1_1_asset.html", null ],
    [ "CryptoTA.Apis.Balance", "class_crypto_t_a_1_1_apis_1_1_balance.html", [
      [ "CryptoTA.Apis.TradingBalance", "class_crypto_t_a_1_1_apis_1_1_trading_balance.html", null ]
    ] ],
    [ "Kraken.Balance2", "class_kraken_1_1_balance2.html", null ],
    [ "Kraken.Balance3", "class_kraken_1_1_balance3.html", null ],
    [ "Kraken.Balance4", "class_kraken_1_1_balance4.html", null ],
    [ "Kraken.Batchadd", "class_kraken_1_1_batchadd.html", null ],
    [ "Kraken.Batchadd2", "class_kraken_1_1_batchadd2.html", null ],
    [ "Kraken.Batchcancel", "class_kraken_1_1_batchcancel.html", null ],
    [ "Kraken.Batchcancel2", "class_kraken_1_1_batchcancel2.html", null ],
    [ "CryptoTA.MainWindow.BitstampOhlc", "class_crypto_t_a_1_1_main_window_1_1_bitstamp_ohlc.html", null ],
    [ "CryptoTA.MainWindow.BitstampOhlcData", "class_crypto_t_a_1_1_main_window_1_1_bitstamp_ohlc_data.html", null ],
    [ "CryptoTA.MainWindow.BitstampOhlcItem", "class_crypto_t_a_1_1_main_window_1_1_bitstamp_ohlc_item.html", null ],
    [ "CryptoTA.MainWindow.BitstampTick", "class_crypto_t_a_1_1_main_window_1_1_bitstamp_tick.html", null ],
    [ "Kraken.Cancel", "class_kraken_1_1_cancel.html", null ],
    [ "Kraken.Cancel2", "class_kraken_1_1_cancel2.html", null ],
    [ "Kraken.Cancel3", "class_kraken_1_1_cancel3.html", null ],
    [ "Kraken.Closed2", "class_kraken_1_1_closed2.html", null ],
    [ "System.Collections.ObjectModel.Collection", null, [
      [ "Kraken.Error", "class_kraken_1_1_error.html", null ],
      [ "Kraken.Spread", "class_kraken_1_1_spread.html", null ],
      [ "Kraken.TickData", "class_kraken_1_1_tick_data.html", null ],
      [ "Kraken.Trade", "class_kraken_1_1_trade.html", null ]
    ] ],
    [ "Kraken.Deposit", "class_kraken_1_1_deposit.html", null ],
    [ "Kraken.Depth", "class_kraken_1_1_depth.html", null ],
    [ "Kraken.Descr", "class_kraken_1_1_descr.html", null ],
    [ "Kraken.Descr2", "class_kraken_1_1_descr2.html", null ],
    [ "Kraken.Descr3", "class_kraken_1_1_descr3.html", null ],
    [ "System.Collections.Generic.Dictionary", null, [
      [ "Kraken.Balance", "class_kraken_1_1_balance.html", null ]
    ] ],
    [ "Kraken.Edit", "class_kraken_1_1_edit.html", null ],
    [ "Kraken.Edit2", "class_kraken_1_1_edit2.html", null ],
    [ "System.Exception", null, [
      [ "Kraken.ApiException< TResult >", "class_kraken_1_1_api_exception.html", null ]
    ] ],
    [ "CryptoTA.MainWindow.ExchangeRateConvertResponse", "class_crypto_t_a_1_1_main_window_1_1_exchange_rate_convert_response.html", null ],
    [ "CryptoTA.Apis.Fees", "class_crypto_t_a_1_1_apis_1_1_fees.html", null ],
    [ "Kraken.Fees", "class_kraken_1_1_fees.html", null ],
    [ "Kraken.History", "class_kraken_1_1_history.html", null ],
    [ "Kraken.History2", "class_kraken_1_1_history2.html", null ],
    [ "System.Windows.Markup.IComponentConnector", null, [
      [ "CryptoTA.AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", null ],
      [ "CryptoTA.AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", null ],
      [ "CryptoTA.DataDownload", "class_crypto_t_a_1_1_data_download.html", null ],
      [ "CryptoTA.DownloadWindow", "class_crypto_t_a_1_1_download_window.html", null ],
      [ "CryptoTA.DownloadWindow", "class_crypto_t_a_1_1_download_window.html", null ],
      [ "CryptoTA.MainWindow", "class_crypto_t_a_1_1_main_window.html", null ],
      [ "CryptoTA.MainWindow", "class_crypto_t_a_1_1_main_window.html", null ],
      [ "CryptoTA.UserControl1", "class_crypto_t_a_1_1_user_control1.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChart", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", null ],
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ],
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ]
    ] ],
    [ "Kraken.Info", "class_kraken_1_1_info.html", null ],
    [ "Kraken.Info2", "class_kraken_1_1_info2.html", null ],
    [ "Kraken.Info3", "class_kraken_1_1_info3.html", null ],
    [ "Kraken.Info4", "class_kraken_1_1_info4.html", null ],
    [ "Kraken.Info5", "class_kraken_1_1_info5.html", null ],
    [ "System.Windows.Markup.InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "System.Windows.Markup.IStyleConnector", null, [
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ],
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ]
    ] ],
    [ "Kraken.KrakenClient", "class_kraken_1_1_kraken_client.html", null ],
    [ "Kraken.Ledger", "class_kraken_1_1_ledger.html", null ],
    [ "Kraken.Lock", "class_kraken_1_1_lock.html", null ],
    [ "Kraken.Lock2", "class_kraken_1_1_lock2.html", null ],
    [ "Kraken.Method", "class_kraken_1_1_method.html", null ],
    [ "Kraken.Methods", "class_kraken_1_1_methods.html", null ],
    [ "Kraken.Methods2", "class_kraken_1_1_methods2.html", null ],
    [ "Kraken.Minimum_amount", "class_kraken_1_1_minimum__amount.html", null ],
    [ "Kraken.KrakenClient.ObjectResponseResult< T >", "struct_kraken_1_1_kraken_client_1_1_object_response_result.html", null ],
    [ "Kraken.Ohlc", "class_kraken_1_1_ohlc.html", null ],
    [ "Kraken.Open2", "class_kraken_1_1_open2.html", null ],
    [ "CryptoTA.Apis.Order", "class_crypto_t_a_1_1_apis_1_1_order.html", null ],
    [ "Kraken.Order", "class_kraken_1_1_order.html", [
      [ "Kraken.Closed", "class_kraken_1_1_closed.html", null ]
    ] ],
    [ "CryptoTA.Apis.OrderBook", "class_crypto_t_a_1_1_apis_1_1_order_book.html", null ],
    [ "CryptoTA.Apis.OrderBookEntry", "class_crypto_t_a_1_1_apis_1_1_order_book_entry.html", null ],
    [ "Kraken.OrderBookEntry", "class_kraken_1_1_order_book_entry.html", null ],
    [ "Kraken.Orders", "class_kraken_1_1_orders.html", null ],
    [ "Kraken.Orders2", "class_kraken_1_1_orders2.html", null ],
    [ "Kraken.Orders3", "class_kraken_1_1_orders3.html", null ],
    [ "Kraken.Pairs", "class_kraken_1_1_pairs.html", null ],
    [ "Kraken.Query", "class_kraken_1_1_query.html", null ],
    [ "Kraken.Query2", "class_kraken_1_1_query2.html", null ],
    [ "Kraken.Query3", "class_kraken_1_1_query3.html", null ],
    [ "Kraken.Recent", "class_kraken_1_1_recent.html", null ],
    [ "Kraken.Recent2", "class_kraken_1_1_recent2.html", null ],
    [ "Kraken.Recent3", "class_kraken_1_1_recent3.html", null ],
    [ "Kraken.Recent4", "class_kraken_1_1_recent4.html", null ],
    [ "System.Windows.ResourceDictionary", null, [
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ],
      [ "REghZy.Themes.Controls", "class_r_egh_zy_1_1_themes_1_1_controls.html", null ]
    ] ],
    [ "Kraken.Response", "class_kraken_1_1_response.html", null ],
    [ "Kraken.Response10", "class_kraken_1_1_response10.html", null ],
    [ "Kraken.Response11", "class_kraken_1_1_response11.html", null ],
    [ "Kraken.Response12", "class_kraken_1_1_response12.html", null ],
    [ "Kraken.Response13", "class_kraken_1_1_response13.html", null ],
    [ "Kraken.Response14", "class_kraken_1_1_response14.html", null ],
    [ "Kraken.Response15", "class_kraken_1_1_response15.html", null ],
    [ "Kraken.Response16", "class_kraken_1_1_response16.html", null ],
    [ "Kraken.Response17", "class_kraken_1_1_response17.html", null ],
    [ "Kraken.Response18", "class_kraken_1_1_response18.html", null ],
    [ "Kraken.Response2", "class_kraken_1_1_response2.html", null ],
    [ "Kraken.Response3", "class_kraken_1_1_response3.html", null ],
    [ "Kraken.Response4", "class_kraken_1_1_response4.html", null ],
    [ "Kraken.Response5", "class_kraken_1_1_response5.html", null ],
    [ "Kraken.Response6", "class_kraken_1_1_response6.html", null ],
    [ "Kraken.Response7", "class_kraken_1_1_response7.html", null ],
    [ "Kraken.Response8", "class_kraken_1_1_response8.html", null ],
    [ "Kraken.Response9", "class_kraken_1_1_response9.html", null ],
    [ "Kraken.Result", "class_kraken_1_1_result.html", null ],
    [ "Kraken.Result10", "class_kraken_1_1_result10.html", null ],
    [ "Kraken.Result11", "class_kraken_1_1_result11.html", null ],
    [ "Kraken.Result12", "class_kraken_1_1_result12.html", null ],
    [ "Kraken.Result13", "class_kraken_1_1_result13.html", null ],
    [ "Kraken.Result14", "class_kraken_1_1_result14.html", null ],
    [ "Kraken.Result15", "class_kraken_1_1_result15.html", null ],
    [ "Kraken.Result16", "class_kraken_1_1_result16.html", null ],
    [ "Kraken.Result17", "class_kraken_1_1_result17.html", null ],
    [ "Kraken.Result18", "class_kraken_1_1_result18.html", null ],
    [ "Kraken.Result19", "class_kraken_1_1_result19.html", null ],
    [ "Kraken.Result2", "class_kraken_1_1_result2.html", null ],
    [ "Kraken.Result20", "class_kraken_1_1_result20.html", null ],
    [ "Kraken.Result21", "class_kraken_1_1_result21.html", null ],
    [ "Kraken.Result22", "class_kraken_1_1_result22.html", null ],
    [ "Kraken.Result23", "class_kraken_1_1_result23.html", null ],
    [ "Kraken.Result24", "class_kraken_1_1_result24.html", null ],
    [ "Kraken.Result25", "class_kraken_1_1_result25.html", null ],
    [ "Kraken.Result3", "class_kraken_1_1_result3.html", null ],
    [ "Kraken.Result4", "class_kraken_1_1_result4.html", null ],
    [ "Kraken.Result5", "class_kraken_1_1_result5.html", null ],
    [ "Kraken.Result6", "class_kraken_1_1_result6.html", null ],
    [ "Kraken.Result7", "class_kraken_1_1_result7.html", null ],
    [ "Kraken.Result8", "class_kraken_1_1_result8.html", null ],
    [ "Kraken.Result9", "class_kraken_1_1_result9.html", null ],
    [ "Kraken.Rewards", "class_kraken_1_1_rewards.html", null ],
    [ "Kraken.Spread2", "class_kraken_1_1_spread2.html", null ],
    [ "CryptoTA.Apis.TickData", "class_crypto_t_a_1_1_apis_1_1_tick_data.html", null ],
    [ "Kraken.Ticker", "class_kraken_1_1_ticker.html", null ],
    [ "Kraken.Ticker2", "class_kraken_1_1_ticker2.html", null ],
    [ "Kraken.Time", "class_kraken_1_1_time.html", null ],
    [ "Kraken.Trade2", "class_kraken_1_1_trade2.html", null ],
    [ "Kraken.Trades", "class_kraken_1_1_trades.html", null ],
    [ "CryptoTA.Apis.TradingPair", "class_crypto_t_a_1_1_apis_1_1_trading_pair.html", null ],
    [ "Kraken.Transaction", "class_kraken_1_1_transaction.html", null ],
    [ "System.Windows.Controls.UserControl", null, [
      [ "CryptoTA.UserControl1", "class_crypto_t_a_1_1_user_control1.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChart", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", null ],
      [ "CryptoTA.UserControls.PointShapeLineChartControl", "class_crypto_t_a_1_1_user_controls_1_1_point_shape_line_chart_control.html", null ]
    ] ],
    [ "Kraken.Volume", "class_kraken_1_1_volume.html", null ],
    [ "CryptoTA.Apis.WebsocketsToken", "class_crypto_t_a_1_1_apis_1_1_websockets_token.html", null ],
    [ "System.Windows.Window", null, [
      [ "CryptoTA.AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", null ],
      [ "CryptoTA.AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", null ],
      [ "CryptoTA.DataDownload", "class_crypto_t_a_1_1_data_download.html", null ],
      [ "CryptoTA.DownloadWindow", "class_crypto_t_a_1_1_download_window.html", null ],
      [ "CryptoTA.DownloadWindow", "class_crypto_t_a_1_1_download_window.html", null ],
      [ "CryptoTA.DownloadWindow", "class_crypto_t_a_1_1_download_window.html", null ],
      [ "CryptoTA.MainWindow", "class_crypto_t_a_1_1_main_window.html", null ],
      [ "CryptoTA.MainWindow", "class_crypto_t_a_1_1_main_window.html", null ],
      [ "CryptoTA.MainWindow", "class_crypto_t_a_1_1_main_window.html", null ]
    ] ],
    [ "Window", null, [
      [ "CryptoTA.AccountsWindow", "class_crypto_t_a_1_1_accounts_window.html", null ]
    ] ],
    [ "Kraken.Withdrawal", "class_kraken_1_1_withdrawal.html", null ],
    [ "Kraken.Withdrawal2", "class_kraken_1_1_withdrawal2.html", null ],
    [ "Kraken.Withdrawal3", "class_kraken_1_1_withdrawal3.html", null ]
];